import { Clock, DollarSign } from "lucide-react";
import Skeleton from "../ui/Skeleton";
import { EmptyState, ErrorState } from "../dashboard/States";
import { formatCurrency, formatHours } from "../../utils/overviewUtils";

export default function OverviewWorkerRevenuAndHours({
  workerStats,
  isLoading,
  error,
  refetch,
}) {
  return (
    <div className="grid gap-4 xl:grid-cols-2">
      {/* WORKER REVENUE */}

      <section className="surface-card overflow-hidden">
        <div className="border-b px-5 py-4">
          <div className="flex items-center gap-2">
            <DollarSign className="text-muted-foreground h-4 w-4" />

            <div>
              <h2 className="text-base font-semibold">Revenue by worker</h2>

              <p className="text-muted-foreground text-xs">
                Total revenue generated by each worker
              </p>
            </div>
          </div>
        </div>

        {isLoading ? (
          <div className="space-y-3 p-5">
            {Array.from({
              length: 5,
            }).map((_, index) => (
              <Skeleton key={index} className="h-14 rounded-xl" />
            ))}
          </div>
        ) : error ? (
          <ErrorState error={error} onRetry={() => refetch()} />
        ) : workerStats.length === 0 ? (
          <EmptyState
            title="No worker revenue yet"
            description="Worker revenue will appear here once bookings have been completed."
          />
        ) : (
          <div className="divide-y max-h-[320px] overflow-auto">
            {workerStats.map((item, index) => (
              <div
                key={item.worker._id}
                className="flex items-center justify-between px-5 py-4"
              >
                <div className="flex items-center gap-3">
                  <div className="bg-muted flex h-9 w-9 items-center justify-center rounded-lg text-sm font-semibold">
                    {index + 1}
                  </div>

                  <div>
                    <p className="text-sm font-medium">{item.worker.name}</p>

                    <p className="text-muted-foreground text-xs">
                      Revenue generated
                    </p>
                  </div>
                </div>

                <p className="text-sm font-semibold">
                  {formatCurrency(Number(item.revenue ?? 0))}
                </p>
              </div>
            ))}
          </div>
        )}
      </section>

      {/* WORKER HOURS */}

      <section className="surface-card overflow-hidden">
        <div className="border-b px-5 py-4">
          <div className="flex items-center gap-2">
            <Clock className="text-muted-foreground h-4 w-4" />

            <div>
              <h2 className="text-base font-semibold">Most working workers</h2>

              <p className="text-muted-foreground text-xs">
                Ranked by total working hours
              </p>
            </div>
          </div>
        </div>

        {isLoading ? (
          <div className="space-y-4 p-5">
            {Array.from({ length: 5 }).map((_, index) => (
              <Skeleton key={index} className="h-16 rounded-xl" />
            ))}
          </div>
        ) : error ? (
          <ErrorState error={error} onRetry={() => refetch()} />
        ) : workerStats.length === 0 ? (
          <EmptyState
            title="No working hours yet"
            description="Worker hours will appear here once bookings are completed."
          />
        ) : (
          <div className="space-y-5 p-5 max-h-[320px] overflow-auto">
            {workerStats.map((item, index) => {
              const workingMinutes = Number(item.workingMinutes ?? 0);
              const hours = workingMinutes / 60;

              const maxMinutes = Math.max(
                Number(workerStats[0]?.workingMinutes ?? 0),
                1,
              );

              const percentage = Math.round(
                (workingMinutes / maxMinutes) * 100,
              );

              return (
                <div key={item.worker._id} className="space-y-2">
                  <div className="flex items-center justify-between gap-4">
                    <div className="flex items-center gap-3">
                      <div className="bg-muted flex h-8 w-8 items-center justify-center rounded-lg text-xs font-semibold">
                        {index + 1}
                      </div>

                      <div>
                        <p className="text-sm font-medium">
                          {item.worker.name}
                        </p>

                        <p className="text-muted-foreground text-xs">
                          {formatHours(hours)}
                        </p>
                      </div>
                    </div>

                    <span className="text-sm font-semibold">
                      {formatHours(hours)}
                    </span>
                  </div>

                  <div className="bg-muted h-2 overflow-hidden rounded-full">
                    <div
                      className="bg-primary h-full rounded-full transition-all"
                      style={{
                        width: `${percentage}%`,
                      }}
                    />
                  </div>
                </div>
              );
            })}
          </div>
        )}
      </section>
    </div>
  );
}
