import { TrendingUp } from "lucide-react";
import { EmptyState, ErrorState } from "../dashboard/States";
import {
  CartesianGrid,
  Line,
  LineChart,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
} from "recharts";
import { formatCurrency } from "../../utils/overviewUtils";
import Skeleton from "../ui/Skeleton";

export default function OverviewRevenu12Months({
  isLoading,
  totalRevenu,
  yearRevenu,
  error,
  refetch,
}) {
  return (
    <section className="surface-card">
      <div className="flex items-center justify-between border-b px-5 py-4">
        <div>
          <div className="flex items-center gap-2">
            <TrendingUp className="text-muted-foreground h-4 w-4" />

            <h2 className="text-base font-semibold">
              Revenue — last 12 months
            </h2>
          </div>

          <p className="text-muted-foreground mt-1 text-xs">
            Monthly revenue generated by the business
          </p>
        </div>

        {!isLoading && totalRevenu && (
          <div className="text-right">
            <p className="text-muted-foreground text-xs">Total</p>

            <p className="text-lg font-semibold">
              {formatCurrency(totalRevenu)}
            </p>
          </div>
        )}
      </div>

      <div className="p-4">
        {isLoading ? (
          <Skeleton className="h-[300px] w-full rounded-xl" />
        ) : error ? (
          <ErrorState error={error} onRetry={() => refetch()} />
        ) : yearRevenu.length === 0 ? (
          <EmptyState
            title="No revenue data"
            description="Monthly revenue will appear here once bookings are available."
          />
        ) : (
          <ResponsiveContainer width="100%" height={300}>
            <LineChart
              data={yearRevenu}
              margin={{
                top: 8,
                right: 8,
                left: -16,
                bottom: 0,
              }}
            >
              <CartesianGrid
                strokeDasharray="3 3"
                stroke="var(--color-border)"
                vertical={false}
              />

              <XAxis
                dataKey="month"
                tick={{
                  fontSize: 12,
                  fill: "var(--color-muted-foreground)",
                }}
                axisLine={false}
                tickLine={false}
              />

              <YAxis
                tick={{
                  fontSize: 12,
                  fill: "var(--color-muted-foreground)",
                }}
                axisLine={false}
                tickLine={false}
              />

              <Tooltip
                formatter={(value) => [
                  formatCurrency(Number(value)),
                  "Revenue",
                ]}
                contentStyle={{
                  background: "var(--color-popover)",
                  border: "1px solid var(--color-border)",
                  borderRadius: "0.75rem",
                  color: "var(--color-popover-foreground)",
                  fontSize: 12,
                }}
              />

              <Line
                type="monotone"
                dataKey="revenue"
                name="Revenue"
                stroke="var(--color-chart-1)"
                strokeWidth={3}
                dot={{
                  r: 4,
                  fill: "var(--color-chart-1)",
                }}
                activeDot={{
                  r: 6,
                }}
              />
            </LineChart>
          </ResponsiveContainer>
        )}
      </div>
    </section>
  );
}
